In [2]:
import numpy as np

In [5]:
A=np.array([[-3/4,3/4],[1,1]]).T
np.matmul(np.linalg.inv(A),[0,1])

array([0.66666667, 0.5       ])

In [4]:
np.matmul([0.66666667, 0.5       ],A)

array([-2.49999998e-09,  1.00000000e+00])

In [19]:
from scipy.linalg import eig

A=np.array([[1/4,3/4],[2/3,1/3]])
eig(A, left=True)

(array([-0.41666667+0.j,  1.        +0.j]),
 array([[-0.70710678, -0.66436384],
        [ 0.70710678, -0.74740932]]),
 array([[-0.74740932, -0.70710678],
        [ 0.66436384, -0.70710678]]))

In [20]:
0.74740932/sum([-0.74740932, -0.70710678])

-0.5138542777216423

In [22]:
-0.70710678/sum([ -0.70710678, -0.74740932])

0.4861457222783577

In [17]:
A

array([[0.25      , 0.66666667],
       [0.75      , 0.33333333]])

In [24]:
mu=np.array([2/3,3/4])
mu/=sum(mu)

A=np.array([[1/4,3/4],[2/3,1/3]])
-A*np.log2(A)

array([[0.5       , 0.31127812],
       [0.389975  , 0.52832083]])

In [29]:

np.sum(np.matmul(mu,-A*np.log2(A)))

0.8679345589507923